package com.example.managementbackend.model.enums;
public enum StressType {
    DROUGHT, OVERWATERING, HEAT, COLD,
    NUTRIENT_DEFICIENCY_N, NUTRIENT_DEFICIENCY_K, NUTRIENT_DEFICIENCY_FE,
    SALINITY, LIGHT_INSUFFICIENT, LIGHT_EXCESSIVE, CO2_IMBALANCE, ROOT_HYPOXIA
}
